# Generated by Django 5.2.5 on 2026-07-30 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
