# Generated by Django 5.2.5 on 2026-07-31 20:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_api', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carttype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='carttype',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='type',
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RemoveField(
            model_name='cart',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='name',
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('status', 1)), fields=('created_by',), name='unique_active_cart_per_user'),
        ),
        migrations.DeleteModel(
            name='CartType',
        ),
    ]
