# Generated by Django 5.2.5 on 2026-02-27 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sale',
            unique_together={('invoice_number',)},
        ),
        migrations.RemoveField(
            model_name='sale',
            name='company_id',
        ),
    ]
