# Generated by Django 5.2.5 on 2026-03-05 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_api', '0002_alter_sale_unique_together_remove_sale_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
