# Generated by Django 5.2.5 on 2026-03-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_api', '0003_alter_sale_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='channel',
            field=models.CharField(
                choices=[
                    ('Walk-in', 'Walk-in'),
                    ('Facebook', 'Facebook'),
                    ('Phone', 'Phone'),
                    ('Website', 'Website'),
                    ('Instagram', 'Instagram'),
                    ('WhatsApp', 'WhatsApp'),
                ],
                db_index=True,
                default='Walk-in',
                max_length=20,
            ),
        ),
    ]
