# Generated by Django 5.2.5 on 2026-03-07 04:15

from django.db import migrations, models


def migrate_sale_statuses(apps, schema_editor):
    Sale = apps.get_model('sale_api', 'Sale')
    Sale.objects.filter(status='DRAFT').update(status='PENDING')
    Sale.objects.filter(status='CANCELLED').update(status='RETURNED')


class Migration(migrations.Migration):

    dependencies = [
        ('sale_api', '0004_sale_channel'),
    ]

    operations = [
        migrations.RunPython(migrate_sale_statuses, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PROCESSING', 'Processing'), ('PACKAGED', 'Packaged'), ('SHIPPED', 'Shipped'), ('OUT_OF_DELIVERY', 'Out of Delivery'), ('DELIVERED', 'Delivered'), ('RETURNED', 'Returned')], default='PENDING', max_length=20),
        ),
    ]
