# Generated by Django 5.2.5 on 2026-03-17 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale_api', '0005_alter_sale_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name': 'Sale', 'verbose_name_plural': 'Sales'},
        ),
        migrations.AlterModelOptions(
            name='saleitem',
            options={'verbose_name': 'Sale Item', 'verbose_name_plural': 'Sale Items'},
        ),
    ]
