# Generated by Django 5.2.5 on 2026-05-21 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_api', '0008_payment_method_and_sale_mapping'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='paymentmethod',
            new_name='sale_api_pa_code_c204b3_idx',
            old_name='sale_api_pa_code_3ef515_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentmethod',
            new_name='sale_api_pa_name_10570c_idx',
            old_name='sale_api_pa_name_7786a7_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentmethod',
            new_name='sale_api_pa_sort_or_eea62f_idx',
            old_name='sale_api_pa_sort_or_7388df_idx',
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
