# Generated by Django 5.2.5 on 2026-03-17 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productpricehistory',
            options={'ordering': ['-changed_at'], 'verbose_name': 'Product Price History', 'verbose_name_plural': 'Product Price Histories'},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['sku'], 'verbose_name': 'Product Variant', 'verbose_name_plural': 'Product Variants'},
        ),
    ]
