# Generated by Django 5.2.5 on 2026-05-23 18:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0003_brand'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AddField(
            model_name='brand',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Display order for brands. Lower values appear first.'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['display_order'], name='brands_display_88dd5d_idx'),
        ),
    ]
