# Generated by Django 5.2.5 on 2026-05-31 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_api', '0003_alter_category_hierarchy'),
        ('product_api', '0004_alter_brand_options_brand_display_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products', to='category_api.category'),
        ),
    ]
