# Generated by Django 5.2.5 on 2026-07-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0006_product_description_product_legacy_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
