# Generated by Django 5.2.5 on 2026-07-15 10:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0009_productimage_default_unique_per_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productimage',
            name='product_image_single_default_per_product',
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_default', True)), fields=('product',), name='product_image_single_default_per_product'),
        ),
    ]
