# Generated by Django 5.2.5 on 2026-07-18 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin_api', '0001_initial'),
        ('product_api', '0010_remove_productimage_product_image_single_default_per_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='origin_api.origin'),
        ),
    ]
