# Generated by Django 5.2.5 on 2026-08-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0011_product_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=1, help_text='Display order for brands. Lower values appear first.'),
        ),
    ]
