# Generated by Django 5.2.5 on 2026-03-17 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0002_user_role_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
