# Generated by Django 5.2.5 on 2026-08-10 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('change_user_username', 'Can change user username'), ('change_user_password', 'Can change user password'), ('assign_user_role', 'Can assign user role'), ('remove_user_role', 'Can remove user role')], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
