# Generated by Django 5.2.5 on 2026-02-07 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('quantity', models.IntegerField()),
                ('movement_type', models.CharField(choices=[('PURCHASE', 'Purchase'), ('SALE', 'Sale'), ('REFUND', 'Refund'), ('ADJUSTMENT', 'Adjustment'), ('OPENING', 'Opening Balance')], max_length=20)),
                ('reference_type', models.CharField(blank=True, choices=[('PURCHASE', 'Purchase'), ('ORDER', 'Order'), ('RETURN', 'Return'), ('MANUAL', 'Manual')], max_length=20, null=True)),
                ('reference_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='product_api.productvariant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product_variant'], name='inventory_a_product_f74e6a_idx'), models.Index(fields=['movement_type'], name='inventory_a_movemen_99db10_idx')],
            },
        ),
    ]
