# Generated by Django 5.2.5 on 2026-03-17 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorymovement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Inventory Movement', 'verbose_name_plural': 'Inventory Movements'},
        ),
    ]
