# Generated by Django 5.2.5 on 2026-03-17 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-purchase_date', '-id'], 'verbose_name': 'Purchase', 'verbose_name_plural': 'Purchases'},
        ),
        migrations.AlterModelOptions(
            name='purchaseitem',
            options={'ordering': ['id'], 'verbose_name': 'Purchase Item', 'verbose_name_plural': 'Purchase Items'},
        ),
    ]
