# Generated by Django 5.2.5 on 2026-03-17 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_api', '0005_rebuild_chartofaccount_codes_with_type_prefix'),
        ('transaction_api', '0005_alter_accountingtransaction_transaction_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccount',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='opening_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='opening_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_accounts', to='transaction_api.accountingtransaction'),
        ),
        migrations.AddIndex(
            model_name='chartofaccount',
            index=models.Index(fields=['opening_date'], name='chart_of_ac_opening_59c3e4_idx'),
        ),
    ]
