# Generated by Django 5.2.5 on 2026-03-17 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_api', '0006_chartofaccount_opening_balance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chartofaccount',
            options={'ordering': ['code', 'id'], 'verbose_name': 'Chart of Account', 'verbose_name_plural': 'Chart of Accounts'},
        ),
    ]
