# Generated by Django 5.2.5 on 2026-03-17 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_api', '0005_alter_accountingtransaction_transaction_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountingtransaction',
            options={'ordering': ['-transaction_date', '-id'], 'verbose_name': 'Accounting Transaction', 'verbose_name_plural': 'Accounting Transactions'},
        ),
        migrations.AlterModelOptions(
            name='accountingtransactionline',
            options={'ordering': ['id'], 'verbose_name': 'Accounting Transaction Line', 'verbose_name_plural': 'Accounting Transaction Lines'},
        ),
    ]
