# Generated by Django 5.2.5 on 2026-03-21 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_api', '0007_alter_accountingtransaction_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountingtransaction',
            options={'ordering': ['-transaction_datetime', '-id'], 'verbose_name': 'Accounting Transaction', 'verbose_name_plural': 'Accounting Transactions'},
        ),
    ]
