# Generated by Django 5.2.5 on 2026-08-30 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('request_id', models.CharField(db_index=True, help_text='Correlation identifier, reused from a valid client X-Request-ID header or generated per request. Not unique: a client that repeats an identifier produces two records.', max_length=64)),
                ('is_authenticated', models.BooleanField(db_index=True, default=False)),
                ('anonymous_id', models.CharField(blank=True, db_index=True, help_text='Client-generated X-Anonymous-ID, when supplied.', max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, help_text='Client address resolved through the configured trusted proxy depth.', null=True)),
                ('forwarded_for', models.CharField(blank=True, help_text='Raw X-Forwarded-For chain, kept as reported and never trusted on its own.', max_length=255)),
                ('user_agent', models.TextField(blank=True, help_text='Raw User-Agent, retained so the parsed fields below can be recomputed if parsing improves.')),
                ('browser', models.CharField(blank=True, max_length=50)),
                ('browser_version', models.CharField(blank=True, max_length=30)),
                ('operating_system', models.CharField(blank=True, max_length=50)),
                ('operating_system_version', models.CharField(blank=True, max_length=30)),
                ('device_type', models.CharField(choices=[('DESKTOP', 'Desktop'), ('MOBILE', 'Mobile'), ('TABLET', 'Tablet'), ('BOT', 'Bot'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('is_mobile', models.BooleanField(default=False)),
                ('is_bot', models.BooleanField(default=False)),
                ('bot_name', models.CharField(blank=True, max_length=50)),
                ('client_type', models.CharField(choices=[('WEB', 'Web'), ('MOBILE', 'Mobile'), ('ADMIN', 'Admin'), ('EXTERNAL', 'External'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('origin', models.CharField(blank=True, max_length=255)),
                ('referer', models.CharField(blank=True, max_length=500)),
                ('frontend_route', models.CharField(blank=True, help_text='Client-supplied X-Client-Route, when supplied.', max_length=255)),
                ('request_method', models.CharField(db_index=True, max_length=10)),
                ('request_path', models.CharField(db_index=True, max_length=500)),
                ('route_pattern', models.CharField(blank=True, help_text='Resolved URL pattern, e.g. /api/v1/products/{pk}/, for aggregation across the many concrete paths that share it.', max_length=255)),
                ('query_parameters', models.JSONField(blank=True, default=dict)),
                ('query_string', models.TextField(blank=True)),
                ('headers', models.JSONField(blank=True, default=dict, help_text='Allow-listed request headers only. Authorization, Cookie and API key headers are never read.')),
                ('request_body', models.JSONField(blank=True, null=True)),
                ('is_multipart', models.BooleanField(default=False)),
                ('form_fields', models.JSONField(blank=True, default=dict)),
                ('files', models.JSONField(blank=True, default=list, help_text='Uploaded file metadata - field name, filename, content type and size. File contents are never stored.')),
                ('file_count', models.PositiveSmallIntegerField(default=0)),
                ('total_file_size_bytes', models.PositiveBigIntegerField(default=0)),
                ('request_size_bytes', models.PositiveBigIntegerField(default=0)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('response_size_bytes', models.PositiveBigIntegerField(default=0)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_success', models.BooleanField(default=True)),
                ('outcome', models.CharField(choices=[('SUCCESS', 'Success'), ('CLIENT_ERROR', 'Client Error'), ('SERVER_ERROR', 'Server Error'), ('EXCEPTION', 'Exception')], default='SUCCESS', max_length=15)),
                ('error_message', models.TextField(blank=True)),
                ('exception_type', models.CharField(blank=True, db_index=True, max_length=255)),
                ('traceback', models.TextField(blank=True)),
                ('error_details', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Request Log',
                'verbose_name_plural': 'API Request Logs',
                'ordering': ['-created_at', '-id'],
                'permissions': [('view_request_log_request_payload', 'Can view request log request payload'), ('view_request_log_response_payload', 'Can view request log response payload'), ('view_request_log_error_details', 'Can view request log error details'), ('view_request_log_traceback', 'Can view request log traceback')],
                'indexes': [models.Index(fields=['route_pattern', '-created_at'], name='request_log_route_p_0e5d95_idx'), models.Index(fields=['status_code', '-created_at'], name='request_log_status__d9fa20_idx'), models.Index(fields=['user', '-created_at'], name='request_log_user_id_c110cb_idx'), models.Index(fields=['outcome', '-created_at'], name='request_log_outcome_4e989e_idx')],
            },
        ),
    ]
