# Generated by Django 5.2.5 on 2026-06-10 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_api', '0003_alter_category_hierarchy'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='legacy_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
