# Generated by Django 5.2.5 on 2026-07-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_api', '0004_category_legacy_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
