# Generated by Django 5.2.5 on 2026-08-21 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_api', '0006_category_show_in_menu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='order',
            new_name='display_order',
        ),
    ]
