# Generated by Django 5.2.5 on 2026-08-23 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_api', '0007_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['display_order', 'name'], 'permissions': [('mark_category_as_menu', 'Can mark category as menu'), ('remove_category_from_menu', 'Can remove category from menu')], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
