# Generated by Django 5.2.5 on 2026-07-23 20:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0011_product_origin'),
        ('review_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_active_review_per_product_user',
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 3), _negated=True), fields=('product', 'created_by'), name='unique_active_review_per_product_user'),
        ),
    ]
