# Generated by Django 5.2.5 on 2026-07-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_api', '0002_remove_review_unique_active_review_per_product_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected')], db_index=True, default=1, verbose_name='Moderation Status'),
        ),
    ]
